name: ElementPlugin
version: '1.1.16'
main: hs.elementPlugin.ElementPlugin
website: https://ko-fi.com/1pumpkinn
api-version: '1.21.8'
load: STARTUP
authors: [ ___Pumpkinn ]
contributors: [ ___Vishini ]

commands:
  trust:
    description: Manage trust relationships
    usage: /trust <list|add|remove|accept|deny> [player]

  element:
    description: Element admin commands
    usage: /element <set|debug> <player> [element]
    permission: element.admin

  mana:
    description: Manage mana (reset or set)
    usage: /mana <reset|set> [player] [amount]
    permission: element.mana

  util:
    description: Get utility items (upgraders and reroller)
    usage: /util
    permission: element.admin

  customblock:
    description: Manage custom blocks (pedestals, reinforced blocks, etc.)
    usage: /customblock <give|list> [block_id] [amount]
    permission: elementsmp.customblock
    aliases: [ cb, cblock ]

  pedestal:
    description: Admin commands for managing pedestals
    usage: /pedestal <info|reload|check|claim|transfer> [player|uuid]
    permission: elementsmp.pedestal.admin
    aliases: [ ped ]

  damagetest:
    description: Spawn test dummies for damage testing
    usage: /damagetest <spawn>
    default: op

  elements:
    description: View information about all elements
    usage: /elements [element_name]
    aliases: [ elementinfo, elinfo ]



permissions:
  element.admin:
    description: Allows use of element admin commands
    default: op

  element.mana:
    description: Allows use of mana management commands
    default: op

  elementsmp.customblock:
    description: Allows use of the customblock command
    default: op

  elementsmp.pedestal.admin:
    description: Allows full admin control of pedestals
    default: op

  elementsmp.pedestal.bypass:
    description: Allows bypassing pedestal ownership checks
    default: op